language: clojure
lein: lein
jdk:
  - oraclejdk8
install:
  - pushd site; lein deps; popd
  - pushd lib; lein deps; popd
script:
  - pushd lib
  - lein run -m build/release
  - lein run -m build/run-all-tests
  - lein test parinfer.test
  - popd
