language: clojure
lein: lein
jdk:
  - oraclejdk8
install:
  - lein deps
  - cd parinfer-lib && lein deps
script:
  - cd parinfer-lib
  - lein run -m build/release
  - lein run -m build/test-runner && node target/cljs-tests/test-runner.js
  - lein test parinfer.test
