language: clojure
lein: lein
jdk:
  - oraclejdk8
install:
  - pushd parinfer-site; lein deps; popd
  - pushd parinfer-lib; lein deps; popd
script:
  - push parinfer-lib
  - lein run -m build/release
  - lein run -m build/test-runner && node target/cljs-tests/test-runner.js
  - lein test parinfer.test
  - popd
